#[derive(Debug, Clone)]
pub enum Action {
    InputChar(char),
    InsertText(String),
    PasteText(String),
    InputBackspace,
    InputDelete,
    InputSubmit,
    CursorWordLeft,
    CursorWordRight,
    DeleteWordLeft,
    RemoveListItem, // Remove empty list item, keep newline
    CursorHome,
    CursorEnd,
    ClearConversation,
    NewContext,
    SelectNextContext,
    SelectPrevContext,
    AppendChars(String),
    StreamDone {
        _input_tokens: usize,
        output_tokens: usize,
        cache_hit_tokens: usize,
        cache_miss_tokens: usize,
        stop_reason: Option<String>,
    },
    StreamError(String),
    ScrollUp(f32),
    ScrollDown(f32),
    StopStreaming,
    TmuxSendKeys {
        pane_id: String,
        keys: String,
    },
    TogglePerfMonitor,
    ToggleConfigView,
    ConfigSelectProvider(crate::llm_types::LlmProvider),
    ConfigSelectAnthropicModel(crate::llm_types::AnthropicModel),
    ConfigSelectGrokModel(crate::llm_types::GrokModel),
    ConfigSelectGroqModel(crate::llm_types::GroqModel),
    ConfigSelectDeepSeekModel(crate::llm_types::DeepSeekModel),
    ConfigSelectNextBar,
    ConfigSelectPrevBar,
    ConfigIncreaseSelectedBar,
    ConfigDecreaseSelectedBar,
    ConfigNextTheme,
    ConfigPrevTheme,
    ConfigToggleAutoContinue,
    ConfigSelectSecondaryProvider(crate::llm_types::LlmProvider),
    ConfigSelectSecondaryAnthropicModel(crate::llm_types::AnthropicModel),
    ConfigToggleReverie,
    OpenCommandPalette,
    ResetSessionCosts,
    SelectContextById(String),
    None,
}

pub enum ActionResult {
    Nothing,
    StopStream,
    StartApiCheck,
    Save,
    SaveMessage(String),
}
