#!/usr/bin/env python3
"""Audit DeepSeek request JSON for cache hit/miss analysis."""
import json
import re
import sys

CHARS_PER_TOKEN = 3.5

def estimate_tokens(text):
    return int(len(text) / CHARS_PER_TOKEN) if text else 0

def extract_panel_timestamp(msg):
    """Extract 'autogenerated_at' from panel assistant messages."""
    if msg.get("role") != "assistant":
        return ""
    content = msg.get("content", "")
    tool_calls = msg.get("tool_calls", [])
    if not tool_calls:
        return ""
    # Extract panel ID
    panel_id = ""
    for tc in tool_calls:
        fn = tc.get("function", {})
        args = fn.get("arguments", "")
        m = re.search(r'"id"\s*:\s*"([^"]+)"', args)
        if m:
            panel_id = m.group(1)
    # Extract timestamp
    m = re.search(r'Panel automatically generated at (\S+)', content)
    ts = m.group(1) if m else ""
    if panel_id or ts:
        return f"{panel_id} @ {ts}" if ts else panel_id
    return ""

def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "/root/tui/.context-pilot/last_requests/main_worker_deepseek_last_request copy.json"
    with open(path) as f:
        data = json.load(f)

    messages = data.get("messages", [])

    # Header
    print(f"{'idx':>4}  {'role':>10}  {'tokens':>7}  {'accumulated':>12}  {'panel_info'}")
    print(f"{'─'*4}  {'─'*10}  {'─'*7}  {'─'*12}  {'─'*40}")

    accumulated = 0
    for i, msg in enumerate(messages):
        role = msg.get("role", "?")

        # Estimate tokens from all text content in the message
        content = msg.get("content", "") or ""
        # For tool calls, also count function arguments
        for tc in msg.get("tool_calls", []):
            fn = tc.get("function", {})
            content += fn.get("arguments", "")

        tokens = estimate_tokens(content)
        accumulated += tokens
        panel_info = extract_panel_timestamp(msg)

        print(f"{i:>4}  {role:>10}  {tokens:>7,}  {accumulated:>12,}  {panel_info}")

    print(f"\n{'':>4}  {'TOTAL':>10}  {accumulated:>7,}")

if __name__ == "__main__":
    main()
